# Generated by Django 5.0.4 on 2024-04-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="employee",
            table=None,
        ),
    ]
