# Generated by Django 5.0.4 on 2024-04-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_alter_employee_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="employee",
            table="empleado",
        ),
    ]
