# Generated by Django 5.0.4 on 2024-04-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_alter_employee_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
