# Generated by Django 5.0.4 on 2024-04-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0004_employee_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="gender",
        ),
    ]
